sudo: required
services:
  - docker
language: python
env:
  - docs=true
  - twine=true
  - BASE=ubuntu:16.04 IMAGE=moshloop/docker-ubuntu1604-ansible os=ubuntu
  - BASE=ubuntu:16.04 IMAGE=moshloop/ansible-run os=ubuntu
  - BASE=ubuntu:16.04 IMAGE=moshloop/docker-ansible-run os=ubuntu
  - BASE=ubuntu:18.04 IMAGE=moshloop/docker-ubuntu1804-ansible os=ubuntu
  - BASE=debian:stretch IMAGE=moshloop/docker-debian-ansible os=ubuntu
  - BASE=centos:7 IMAGE=moshloop/docker-centos7-ansible os=centos

python:
  - 3.6.5
script:
  - |
    if [[ "$docs" == "true" ]]; then
      pip install mkdocs mkdocs-material pymdown-extensions Pygments
      git remote add docs "https://$GH_TOKEN@github.com/moshloop/ansible-run.git"
      git fetch docs && git fetch docs gh-pages:gh-pages
      mkdocs gh-deploy -v --remote-name docs
    elif [[ "$twine" == "true" ]]; then
      pip install twine
      python setup.py sdist
      twine upload dist/*.tar.gz
    else
      cd Dockerfiles && make $os
    fi