#!/bin/bash

if [[ "$1" == "--help" || "$1" == "" ]]; then
    echo "USAGE: ansible-role role"
    echo "Executes an ansible role directly without requiring it be used within a playbook"
    exit 0

fi
play=$(mktemp)
echo - {hosts: all, roles: [$1]} > $play
ansible-playbook -i 'localhost, ' -c local $play
rm $play